services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  books-backend:
    build:
      context: ./books-backend
      dockerfile: Dockerfile
    container_name: books-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/booksdb

  books-frontend:
    build:
      context: ./books-frontend
      dockerfile: Dockerfile
    container_name: books-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - books-backend

volumes:
  mongodb_data:
    driver: local