apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: books
servers: 1
agents: 1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
