apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: books-app
data:
  MONGO_INITDB_DATABASE: booksdb

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: books-app
type: Opaque
data:
  # base64("admin")
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  # base64("password")
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: books-app
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongo
          envFrom:
            - configMapRef:
                name: mongodb-config
            - secretRef:
                name: mongodb-secret
          readinessProbe:
            tcpSocket:
              port: "mongo"
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: "mongo"
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: books-app
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
  type: ClusterIP