apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: books-app
data:
  SERVER_PORT: "8080"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: books-app
type: Opaque
data:
  # base64("mongodb://admin:password@mongodb:27017/booksdb?authSource=admin")
  SPRING_DATA_MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGI6MjcwMTcvYm9va3NkYj9hdXRoU291cmNlPWFkbWlu

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-backend
  namespace: books-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-backend
  template:
    metadata:
      labels:
        app: books-backend
    spec:
      containers:
        - name: books-backend
          image: gochot/books-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          readinessProbe:
            tcpSocket:
              port: "http"
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: "http"
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: books-backend
  namespace: books-app
spec:
  selector:
    app: books-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP