name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build & Push Spring Boot Backend (multi-arch)
      - name: Build & Push Backend Image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./books-backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/books-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/books-backend:${{ github.sha }}

      # Build & Push React Frontend (multi-arch)
      - name: Build & Push Frontend Image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./books-frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/books-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/books-frontend:${{ github.sha }}
