name: CI

on:
  push:
    branches: [ "**" ]
    paths:
      - "books-backend/**"
      - "books-frontend/**"
      - "docker-compose.yml"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "books-backend/**"
      - "books-frontend/**"
      - "docker-compose.yml"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: "21"
  NODE_VERSION: "20"
  MONGODB_URI: "mongodb://localhost:27017/booksdb"

jobs:
  backend:
    name: Backend (Spring Boot + Maven)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Start MongoDB via Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          # Wait for MongoDB to accept connections on 27017
          for i in {1..60}; do
            nc -z 127.0.0.1 27017 && echo "MongoDB is up" && break
            echo "Waiting for MongoDB ($i/60)…"
            sleep 2
          done
          nc -z 127.0.0.1 27017 || (echo "MongoDB did not start in time" && docker compose logs && exit 1)

      - name: Make Maven wrapper executable (if present)
        run: |
          if [ -f books-backend/mvnw ]; then chmod +x books-backend/mvnw; fi

      - name: Test (Maven)
        env:
          SPRING_DATA_MONGODB_URI: ${{ env.MONGODB_URI }}
        run: |
          MVN="mvn"
          [ -f "books-backend/mvnw" ] && MVN="./mvnw"
          $MVN -f books-backend/pom.xml -B -ntp clean verify

      - name: Upload backend test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: |
            books-backend/**/target/surefire-reports/**
            books-backend/**/target/failsafe-reports/**
          if-no-files-found: ignore

      - name: Stop Docker Compose
        if: always()
        run: docker compose -f docker-compose.yml down -v

  frontend:
    name: Frontend (React)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: books-frontend/package-lock.json

      - name: Install dependencies
        working-directory: books-frontend
        run: npm ci

      - name: Lint (if present)
        working-directory: books-frontend
        run: npm run lint --if-present

      - name: Test (if present)
        working-directory: books-frontend
        run: npm run test --if-present -- --ci --watchAll=false

      - name: Build (if present)
        working-directory: books-frontend
        run: npm run build --if-present

      - name: Upload frontend build (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: books-frontend/build
          if-no-files-found: ignore
